# Site settings
name: yefan
location: 厦门
company: VV Technology Co., Ltd.
position: Java开发工程师
github: https://sulaymanyf.github.io/
facebook: https://www.facebook.com/yefan.sulayman
phone: xx
email: yefansulayman@gmail.com

baseurl: "https://sulaymanyf.github.io/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

